name: HardcoreCustom
version: 1.4
main: me.hardcore.HardcorePlugin
api-version: 1.21
depend: [PlaceholderAPI]

commands:
  hoisinh:
    description: GUI hồi sinh
  hardcore:
    description: Reload plugin
