name: HardcoreCustom
version: 1.3
main: me.hardcore.HardcorePlugin
api-version: 1.21

commands:
  hoisinh:
    description: Hồi sinh người chơi hết mạng
    usage: /hoisinh <tên>
  hardcore:
    description: Reload plugin
    usage: /hardcore reload
